import type { ReactNode } from "react"

// Metadata (Open Graph, Twitter, product:* tags) + JSON-LD schema are all
// generated by page.tsx, which does a single server-side fetch. This layout
// exists only as a pass-through route segment.
export default function ProductLayout({ children }: { children: ReactNode }) {
  return children
}
